DELETE FROM enderecos WHERE EXISTS (SELECT 1 FROM enderecos);
DELETE FROM cursos_alunos WHERE EXISTS (SELECT 1 FROM cursos_alunos);
DELETE FROM cursos WHERE EXISTS (SELECT 1 FROM cursos);
DELETE FROM alunos WHERE EXISTS (SELECT 1 FROM alunos);
DELETE FROM professores WHERE EXISTS (SELECT 1 FROM professores);
DELETE FROM pessoas WHERE EXISTS (SELECT 1 FROM pessoas);
DELETE FROM contatos WHERE EXISTS (SELECT 1 FROM contatos);
