DELETE FROM enderecos WHERE EXISTS (SELECT 1 FROM enderecos);
DELETE FROM alunos WHERE EXISTS (SELECT 1 FROM alunos);
DELETE FROM professores WHERE EXISTS (SELECT 1 FROM alunos);
DELETE FROM pessoas WHERE EXISTS (SELECT 1 FROM pessoas);
DELETE FROM contatos WHERE EXISTS (SELECT 1 FROM contatos);
DELETE FROM cursos WHERE EXISTS (SELECT 1 FROM alunos);